service: ebook-store-api

frameworkVersion: '2'

custom:
  settings:
    PRODUCTS_TABLE: products

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  environment: ${self:custom.settings}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'

functions:
  getBooks:
    handler: lambdas/controllers/shop.getBooks
    events:
      - http:
          path: getBooks
          method: GET
          cors: true
  getBook:
    handler: lambdas/controllers/shop.getBook
    events:
    - http:
        path: /getBook/{id}
        method: GET
        cors: true

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.PRODUCTS_TABLE}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1